### ISSUE TITLE
motore can't compile

### ISSUE THREAD

**Issue by pokerchina** [cloudwego/volo#173]
error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/index.crates.io-6f17d22bba15001f/motore-0.3.3/src/make/make_connection.rs:31:23
   |
31 |     type Future<'s> = impl Future<Output = Result<Self::Connection, Self::Error>> + Send + 's where Self: 's, Address:'s;
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/index.crates.io-6f17d22bba15001f/motore-0.3.3/src/service/ext/map_err.rs:23:24
   |
23 |     type Future<'cx> = impl Future<Output = Result<Self::Response, Self::Error>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/index.crates.io-6f17d22bba15001f/motore-0.3.3/src/service/ext/map_response.rs:22:24
   |
22 |     type Future<'cx> = impl Future<Output = Result<Self::Response, Self::Error>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/index.crates.io-6f17d22bba15001f/motore-0.3.3/src/service/service_fn.rs:54:24
   |
54 |     type Future<'cx> = impl Future<Output= Result<R, E>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/index.crates.io-6f17d22bba15001f/motore-0.3.3/src/timeout.rs:34:24
   |
34 |     type Future<'cx> = impl Future<Output = Result<S::Response, Self::Error>> + 'cx;
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/index.crates.io-6f17d22bba15001f/motore-0.3.3/src/utils/either.rs:42:24
   |
42 |     type Future<'cx> = impl Future<Output = Result<Self::Response, Self::Error>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/lightings/.cargo/registry/src/index.crates.io-6f17d22bba15001f/motore-0.3.3/src/lib.rs:2:12
  |
2 | #![feature(impl_trait_in_assoc_type)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0635]: unknown feature `impl_trait_in_assoc_type`
 --> /Users/lightings/.cargo/registry/src/index.crates.io-6f17d22bba15001f/motore-0.3.3/src/lib.rs:2:12
  |
2 | #![feature(impl_trait_in_assoc_type)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0554, E0635, E0658.
For more information about an error, try `rustc --explain E0554`.
error: could not compile `motore` (lib) due to 8 previous errors

**Comment by PureWhiteWu** [comment]
Hello, this is due to the latest changes in nightly rustc. You can upgrade to the latest nightly.

**Comment by PureWhiteWu** [comment]
If you still encounter problems, feel free to reopen this issue.

**Comment by pokerchina** [comment]
rustc --version
rustc 1.71.0-nightly (473f916d8 2023-05-03)

**Comment by PureWhiteWu** [comment]
I've checked that motore can compile on `rustc 1.71.0-nightly (473f916d8 2023-05-03)`.
Did you specify the toolchain version in something like `rust-toolchain.toml` in your project?

**Comment by pokerchina** [comment]
[toolchain]
# TODO: we can remove this toolchain file when TAIT hits stable.
# Related issue: https://github.com/rust-lang/rust/issues/63063.
channel = "nightly"

**Comment by pokerchina** [comment]
[toolchain]
# TODO: we can remove this toolchain file when TAIT hits stable.
# Related issue: https://github.com/rust-lang/rust/issues/63063.
channel = "nightly"

**Comment by pokerchina** [comment]
Maybe M1 chip

**Comment by PureWhiteWu** [comment]
I'm also developing using M1 chip, and it works well.
```
error[E0554]: #![feature] may not be used on the stable release channel
```
This error indicates you are using the stable release channel, you should use nightly instead.
You may try
```
rustup default nightly
```
and try again.

**Comment by pokerchina** [comment]
rustup default nightly
info: using existing install for 'nightly-aarch64-apple-darwin'
info: default toolchain set to 'nightly-aarch64-apple-darwin'

  nightly-aarch64-apple-darwin unchanged - rustc 1.71.0-nightly (473f916d8 2023-05-03)

info: note that the toolchain 'nightly-aarch64-apple-darwin' is currently in use (overridden by '/Users/lightings/works/R/volo-example/rust-toolchain.toml')

**Comment by PureWhiteWu** [comment]
Can it compile now?

**Comment by pokerchina** [comment]
yes

**Comment by pokerchina** [comment]
offcause , can't compile

**Comment by PureWhiteWu** [comment]
Still can't compile? What's the error now?

**Comment by pokerchina** [comment]
问题没有解决，依然存在，提示信息就表示 不支持 impl_trait_in_assoc_type

**Comment by PureWhiteWu** [comment]
完整的错误信息能发一下么？

**Comment by pokerchina** [comment]
error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/make/make_connection.rs:31:23
   |
31 |     type Future<'s> = impl Future<Output = Result<Self::Connection, Self::Error>> + Send + 's where Self: 's, Address:'s;
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/service/ext/map_err.rs:23:24
   |
23 |     type Future<'cx> = impl Future<Output = Result<Self::Response, Self::Error>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/service/ext/map_response.rs:22:24
   |
22 |     type Future<'cx> = impl Future<Output = Result<Self::Response, Self::Error>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/service/service_fn.rs:54:24
   |
54 |     type Future<'cx> = impl Future<Output= Result<R, E>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/timeout.rs:34:24
   |
34 |     type Future<'cx> = impl Future<Output = Result<S::Response, Self::Error>> + 'cx;
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/utils/either.rs:42:24
   |
42 |     type Future<'cx> = impl Future<Output = Result<Self::Response, Self::Error>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/lib.rs:2:12
  |
2 | #![feature(impl_trait_in_assoc_type)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0635]: unknown feature `impl_trait_in_assoc_type`
 --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/lib.rs:2:12
  |
2 | #![feature(impl_trait_in_assoc_type)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0554, E0635, E0658.
For more information about an error, try `rustc --explain E0554`.
error: could not compile `motore` due to 8 previous errors

**Comment by pokerchina** [comment]
error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/make/make_connection.rs:31:23
   |
31 |     type Future<'s> = impl Future<Output = Result<Self::Connection, Self::Error>> + Send + 's where Self: 's, Address:'s;
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/service/ext/map_err.rs:23:24
   |
23 |     type Future<'cx> = impl Future<Output = Result<Self::Response, Self::Error>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/service/ext/map_response.rs:22:24
   |
22 |     type Future<'cx> = impl Future<Output = Result<Self::Response, Self::Error>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/service/service_fn.rs:54:24
   |
54 |     type Future<'cx> = impl Future<Output= Result<R, E>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/timeout.rs:34:24
   |
34 |     type Future<'cx> = impl Future<Output = Result<S::Response, Self::Error>> + 'cx;
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0658]: `impl Trait` in type aliases is unstable
  --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/utils/either.rs:42:24
   |
42 |     type Future<'cx> = impl Future<Output = Result<Self::Response, Self::Error>> + 'cx
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/lib.rs:2:12
  |
2 | #![feature(impl_trait_in_assoc_type)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0635]: unknown feature `impl_trait_in_assoc_type`
 --> /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/lib.rs:2:12
  |
2 | #![feature(impl_trait_in_assoc_type)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0554, E0635, E0658.
For more information about an error, try `rustc --explain E0554`.
error: could not compile `motore` due to 8 previous errors

Caused by:
  process didn't exit successfully: `rustc --crate-name motore --edition=2021 /Users/lightings/.cargo/registry/src/github.com-1ecc6299db9ec823/motore-0.3.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=189 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=99ed2e339449d8ae -C extra-filename=-99ed2e339449d8ae --out-dir /Users/lightings/works/R/volo-example/target/debug/deps -L dependency=/Users/lightings/works/R/volo-example/target/debug/deps --extern futures=/Users/lightings/works/R/volo-example/target/debug/deps/libfutures-fb951dbdfd07b477.rmeta --extern motore_macros=/Users/lightings/works/R/volo-example/target/debug/deps/libmotore_macros-6fd922e50cb490c1.dylib --extern pin_project=/Users/lightings/works/R/volo-example/target/debug/deps/libpin_project-2f899cfd70340283.rmeta --extern tokio=/Users/lightings/works/R/volo-example/target/debug/deps/libtokio-9bb3d3d7d5157e1b.rmeta --cap-lints allow` (exit status: 1)
warning: build failed, waiting for other jobs to finish...

**Comment by pokerchina** [comment]
--edition=2021

**Comment by PureWhiteWu** [comment]
你还是用了 stable 的 rustc，你的 rust 是通过 rustup 安装的么？有没有通过 brew 或者啥装过？

**Comment by PureWhiteWu** [comment]
你 cargo --version 看下输出？

**Comment by pokerchina** [comment]
cargo --version
cargo 1.71.0-nightly (ac8401032 2023-05-02)

**Comment by pokerchina** [comment]
是的brew 安装的

**Comment by PureWhiteWu** [comment]
那我怀疑是 brew 安装导致的问题，你把 brew 安装的卸载了，用 rustup 进行管理吧。

**Comment by pokerchina** [comment]
可以了,

**Comment by pokerchina** [comment]
process didn't exit successfully: `/Users/lightings/works/R/volo-example/target/debug/build/volo-gen-39ad5291114c3c8c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=volo.yml

  --- stderr
  thread 'main' panicked at 'normalize path failed: idl/volo_add.thrift',

**Comment by pokerchina** [comment]
用volo add 一个协议文件，出现这样错，不知什么错误

**Comment by PureWhiteWu** [comment]
你的路径确认存在么？

**Comment by pokerchina** [comment]
entries:
  default:
    protocol: thrift
    filename: volo_gen.rs
    idls:
    - source: local
      path: idl/volo_add.thrift
      ignore_unused: true
